### ISSUE TITLE
Prerendering failed because of error: Error: Cannot find module 'ClientApp/dist/server/main.js'

### ISSUE THREAD

**Issue by hflexgrig** [PieterjanDeClippel/Ssr2024#2]
Hello, I just cloned your repo , and getting that error, am I missing something ?  
Btw I'm using Mac M1 , not sure if it matters.

**Comment by PieterjanDeClippel** [comment]
You have to wait until the file is generated and then refresh your browser.

Or you can comment out the `BootModuleBuilder` and run `npm run build:ssr` manually

**Comment by hflexgrig** [comment]
> You have to wait until the file is generated and then refresh your browser.
> 
> Or you can comment out the `BootModuleBuilder` and run `npm run build:ssr` manually

It worked, thanks a lot :)
